# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: On changes to .github

on:
  push:
    paths-ignore:
      - "./.github/**"

jobs:
  harden-ci-security:
    uses: ./.github/workflows/harden-ci-security.yml
    with:
      target: ${{ github.event.ref }}
